ALTER TABLE riders
ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7),
ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7),
ADD COLUMN IF NOT EXISTS location_accuracy NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMPTZ;

